version: "3"

services:
  devopsdb:
    image: venusama/automation:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 3
    networks:
      - my_network

  application:
    image: venusama/automation:appimage
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    networks:
      - my_network
    depends_on:
      - devopsdb

networks:
  my_network:
    driver: overlay
      

      

