version: "3.9"

services:
  devopsdb:
    image: venusama/august-rev:db
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      - my_network

  application:
    image: venusama/august-rev:app
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    depends_on:
      - devopsdb  
    networks:
      - my_network


networks:
  my_network:
    driver: overlay
      

      

